package sep3.db.network;

public enum NetworkType {
    QUERY, USER, ERROR, BUSINESSLIST, BUSINESS, EDITBUSINESS, SERVICE, EMPLOYEE, REMOVEEMPLOYEE, EMPLOYEELIST, SERVICELISTBYBUSINESSID, SERVICELISTBYTITLE, SERVICELIST, CREATE_USER;
}
