package sep3.rest.appmngt.network;

public enum NetworkType {
    QUERY, USER, ERROR, BUSINESSOWNER, BUSINESSLIST, BUSINESS, SERVICE, EMPLOYEE, REMOVEEMPLOYEE, EMPLOYEELIST, SERVICELIST, SERVICELISTBYBUSINESSID, SERVICELISTBYTITLE,;
}
