package sep3.rest.appmngt.network;

public enum NetworkType {
    QUERY, USER, ERROR, BUSINESSOWNER, BUSINESSLIST, BUSINESS, EDITBUSINESS, SERVICE, EMPLOYEE, REMOVEEMPLOYEE, EMPLOYEELIST, SERVICELIST, SERVICELISTBYBUSINESSID, SERVICELISTBYTITLE, CREATE_USER, BOOK_APPOINTMENT, LIST_APPOINTMENTS;
}
